var mathtriviaquestions= [
["math", "easy", "A triangle with three equal sides is called what?", "Equilateral"],
["math", "easy", "A triangle with two equal sides is called what?", "Isosceles"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
["math", "easy", "question", "answer"],
];