const oldpaintings = [
	{
	  name:'A Lone Barn',
	  img:'1 ALoneBarn.jpg',
	  price:5,
	  sold:2,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari - This item is for sale upon special request',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Cliff Side',
	  img:'2 CliffSide.jpg',
	  price:5,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari - This item is for sale upon special request',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'A Journey Left By The Adventurer',
	  img:'3 AJourneyLeftByTheAdventurer.jpg',
	  price:5,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari - This item is for sale upon special request',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Saavy Tsunami',
	  img:'4 SavvyTsunami.jpg',
	  price:10,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari - This item is for sale upon special request',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Woman Alone',
	  img:'5 WomanAlone.jpg',
	  price:20,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Awaiting Death',
	  img:'6 AwaitingDeath.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Skater Boi',
	  img:'7 SkaterBoi.jpg',
	  price:15,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"  
	},
	{
	  name:'The Lone Tree Weeps During Sunset',
	  img:'8 TheLoneTreeWeepsDuringSunset.jpg',
	  price:30,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  buycode:'BET7YW6UH4886',
	  type: "painting",
	  creator: "Robert Calamari"  
	},
	{
	  name:'When Death Arises',
	  img:'9 WhenDeathArises.jpg',
	  price:10,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari - This item is for sale upon special request',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Floating Island',
	  img:'10 FloatingIsland.jpg',
	  price:20,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"  
	},
	{
	  name:'Alone',
	  img:'11 Alone.jpg',
	  price:15,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'2Z67VXF5CF3E6'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Fall Time By The Lake',
	  img:'12 FallTimeByTheLake.jpg',
	  price:40,
	  sold:2,
	  material:'Oil on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Cowboy At Dusk Time',
	  img:'13 CowboyAtDuskTime.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Nighttime Lake',
	  img:'13 NighttimeLake.jpg',
	  price:25,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'9Y8LXUBZ6K9D2'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Chasing',
	  img:'14 Chasing.jpg',
	  price:15,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'5RZTB6ZXEV2PN'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'I Hate Painting Trees',
	  img:'15 IHatePaintingTrees.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Fox',
	  img:'16 Fox.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Water Lillies by Monet',
	  img:'16 WaterLillies.jpg',
	  price:25,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'33DLC8XGUDWB4'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'The Far Beyond',
	  img:'17 TheFarBeyond.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'L.A. Sunset',
	  img:'18 LASunset.jpg',
	  price:40,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'White Flowers Flourish In Spring',
	  img:'19 WhiteFlowersFlourishInSpring.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'The Morning Aftermath',
	  img:'20 TheMorningAftermath.jpg',
	  price:40,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'The Infinite Garden',
	  img:'21 TheInfiniteGarden.jpg',
	  price:50,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Balancing Good And Even',
	  img:'22 BalancingGoodAndEven.jpg',
	  price:40,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'E6FEGSPFFU9LY'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Bird Bath Break',
	  img:'23 BirdBathBreak.jpg',
	  price:50,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Theres Always More To Explore',
	  img:'24 TheresAlwaysMoreToExplore.jpg',
	  price:50,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'748XYUQK4GXAU'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Peeping Tom',
	  img:'25 PeepingTom.jpg',
	  price:50,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Dark Daisy',
	  img:'26 DarkDaisy.jpg',
	  price:50,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Super Mario 64',
	  img:'27 SuperMario64.jpg',
	  price:75,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'3MLG8FMADHZCC'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Love Comes In All Shapes And Sizes',
	  img:'28 LoveComesInAllShapesAndSizes.jpg',
	  price:40,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'I Call This One Bold And Brash',
	  img:'29 ICallThisOneBoldAndBrash.JPG',
	  price:40,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  buycode:'F9N2NZ8BH4QWA' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Mysterious Night',
	  img:'30 MysteriousNight.jpg',
	  price:200,
	  sold:2,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"  
	},
	{
	  name:'Beach Bum Days',
	  img:'31 BeachBumDays.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'City Of Love',
	  img:'32 CityOfLove.jpg',
	  price:40,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Origins',
	  img:'33 Origins.jpg',
	  price:75,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'18x24 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Red Hot Chili Peppers',
	  img:'34 RedHotChiliPeppers.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'The Crap Nebula',
	  img:'35 TheCrapNebula.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Red Delicious Apple',
	  img:'36 RedDeliciousApple.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'My Dad',
	  img:'37 MyDad.jpg',
	  price:'Priceless',
	  sold:1,
	  material:'Acrylic on Tile',
	  size:'12x20 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"  
	},
	{
	  name:'Dreary Trees',
	  img:'38 DrearyTrees.jpg',
	  price:80,
	  sold:2,
	  material:'Oil on Canvas Board',
	  size:'16x20 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Pumpkin',
	  img:'39 Pumpkin.jpg',
	  price:60,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Surfer Girl',
	  img:'40 SurferGirl.JPG',
	  price:50,
	  sold:2,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Walking For Miles',
	  img:'41 WalkingForMiles.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'18x24 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Observing',
	  img:'42 Observing.jpg',
	  price:75,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'16x20 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Tweeting',
	  img:'43 Tweeting.jpg',
	  price:60,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'BKN9CTU2FJFF4'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Hawaii Beach',
	  img:'44 HawaiiBeach.jpg',
	  price:60,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'20x24 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Blue Daisy',
	  img:'45 BlueDaisy.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Red Rose',
	  img:'46 RedRose.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Family Photo',
	  img:'47 FamilyPhoto.jpg',
	  price:'Priceless',
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Looking Up',
	  img:'48 LookingUp.jpg',
	  price:75,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Western Sky',
	  img:'49 WesternSky.jpg',
	  price:200,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari',
	  buycode:'7BLKUFQCD4F7L'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Midnight Bay',
	  img:'50 MidnightBay.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Fishing',
	  img:'51 Fishing.jpg',
	  price:70,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Sunflower',
	  img:'52 Sunflower.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'New Jersey Beach',
	  img:'53 NewJerseyBeach.jpg',
	  price:60,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Waterfall Amongst The Night',
	  img:'54 WaterfallAmongstTheNight.jpg',
	  price:40,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'18x24 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Water Lilies 2',
	  img:'55 WaterLilies.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'24x48 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Purple Flower',
	  img:'56 PurpleFlower.jpg',
	  price:50,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Two Deers',
	  img:'57 TwoDeers.jpg',
	  price:100,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari',
	  buycode:'PPXKK5LX4FWGG'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Space Tree',
	  img:'58 SpaceTree.jpg',
	  price:60,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Flying Away',
	  img:'59 FlyingAway.jpg',
	  price:40,
	  sold:1,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Borderline Good',
	  img:'60 BorderlineGood.jpg',
	  price:60,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari',
	  buycode:'ZZJ2DBG8GF82L' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Conquering The Wall',
	  img:'61 ConqueringTheWall.jpg',
	  price:30,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'L6JSLRDK9WZW2' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'The World Above',
	  img:'62 TheWorldAbove.jpg',
	  price:125,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'18x24 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Harry Potter Emblem',
	  img:'63 HarryPotterEmblem.jpg',
	  price:150,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'The Last EC',
	  img:'64 TheLastEC.jpg',
	  price:1,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Colorize',
	  img:'65 Colorize.jpg',
	  price:60,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  buycode:'U85JB494BV3KY'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'More Treasures Than Pockets',
	  img:'66 MoreTreasuresThanPockets.jpg',
	  price:80,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Feelings',
	  img:'J1 Tree.jpg',
	  price:500,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'QGT2PUG5A4ZZU',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Piano Man',
	  img:'J2 Piano Man.jpg',
	  price:100,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'JL53233SEHRB4',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Warming Walk',
	  img:'J3 Warming Walk.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'World Of Color',
	  img:'J4 World Of Color.jpg',
	  price:125,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'V E Day',
	  img:'J5 V E D.jpg',
	  price:200,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'5DYYSX45RDC9J',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Big Moon',
	  img:'J6 Big Moon.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Bliss With Miss',
	  img:'J7 Bliss With Miss.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Hawaii Bay',
	  img:'J8 Hawaii Bay.jpg',
	  price:350,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Big City Girl',
	  img:'J9 Big City Girl.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Tree Of Life',
	  img:'J10 Tree Of Life.jpg',
	  price:450,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Bob Ross Mountains',
	  img:'J11 Bob Ross Mountains.jpg',
	  price:125,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Philly Love',
	  img:'J12 Philly Love.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Sunset? You bet!',
	  img:'J13 Sunset You bet.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Happy Little Wave',
	  img:'J14 Wave.jpg',
	  price:100,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'Z2X4V247JHTSL',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Perfect Proposal',
	  img:'J15 Perfect Proposal.jpg',
	  price:800,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'Z5GC9FY3LRM6N',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Boarding Babe',
	  img:'J16 Boarding Babe.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Be Unique',
	  img:'J17 Be Unique.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Hawaii Palm Trees',
	  img:'J18 Hawaii Palm Trees.jpg',
	  price:100,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Where Dreams Come True',
	  img:'J19 Where Dreams Come True.jpg',
	  price:150,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'AF2MRGJEB3HTL',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Elephi',
	  img:'J20 Elephants.jpg',
	  price:350,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'Unknown',
	  description: 'Jeremy',
	  buycode:'3KPHSKTQAEEUQ',
	  type: "painting",
	  creator: "Jeremy Louie"
	},
	{
	  name:'Bluejay',
	  img:'67 Bluejay.jpg',
	  price:60,
	  sold:0,
	  material:'Oil on Canvas Board',
	  size:'8x10 in',
	  description: 'An Original Calamari',
	  buycode:'MCBVSJY5GUZ7S' ,
	  type: "painting",
	  creator: "Robert Calamari" 
	},
	{
	  name:'Crap Nebula Over Calm Lake',
	  img:'68 CrapNebulaOverCalmLake.jpg',
	  price:60,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'M8G54ZTGXFUYE',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'900 Nautical Miles Away',
	  img:'69 900NauticalMilesAway.jpg',
	  price:200,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'18x24 in',
	  description: 'An Original Calamari',
	  buycode:'3NHSKBFAJVT2A'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Butterfly Spiral Dance',
	  img:'70 ButterflySpiralDance.jpg',
	  price:200,
	  sold:1,
	  material:'Oil on Canvas',
	  size:'30x30 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Water Hole Gang',
	  img:'71 WaterHoleGang.jpg',
	  price:60,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'WN2FCC8B4JFAQ'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Wave Splash',
	  img:'72 WaveSplash.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'FRRDLMM7W85SG'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Firecracker Splat - Boy Sad',
	  img:'73 FirecrackerSplat-BoySad.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'V3BQN4K95KJXN'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Marble Tin',
	  img:'74 MarbleTin.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'QCBG62LQKL5ZW'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Planet Of Blood',
	  img:'75 PlanetOfBlood.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'Z5S626G9REMC2'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'The Internal Void Of Existence',
	  img:'76 TheInternalVoidOfExistence.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'ARQ4R2SEN5732'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Lightning Hitting You On A Crazy Trip',
	  img:'77 LightningHittingYouOnACrazyTrip.jpg',
	  price:30,
	  sold:1,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Bubble Gum Princess Pop',
	  img:'78 Bubble Gum Princess Pop.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'8KX6WY4M6VYK2'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'90s Wind Breaker',
	  img:'79 90s Wind Breaker.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas Board',
	  size:'11x14 in',
	  description: 'An Original Calamari',
	  buycode:'HRFAMW8JSUWVS'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Tree Of Burning Regret',
	  img:'80 TreeOfBurningRegret.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'4LDYA8Y35PWEG'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Rocky Planet',
	  img:'81 RockyPlanet.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'VYNGNDS62R6JJ'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Crap Nebula Up Close',
	  img:'82 Crap Nebula Up Close.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'18x24 in',
	  description: 'An Original Calamari',
	  buycode:'Q3YJW8G3225ZE'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Flower Buds',
	  img:'83 Flower Buds.jpg',
	  price:30,
	  sold:0,
	  material:'Oil on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'8PP4SREJVV92J'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'84 Keeping It Cool',
	  img:'84 Keeping It Cool.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'8GDLYPWU58J5E'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Earth 3038',
	  img:'85 Earth 3038.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'H5QD2M9L4PHWN'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Rainstorm On A Windshield',
	  img:'86 Rainstorm On A Windshield.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'4EWSCMBVNDZPG'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'More Cheese Please',
	  img:'87 More Cheese Please.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'NKH8Q6HUHVEB4'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Space Painting 1',
	  img:'88 Space Painting 1.jpg',
	  price:15,
	  sold:1,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Space Painting 2',
	  img:'89 Space Painting 2.jpg',
	  price:15,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'KD5G662EPM2AC'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Alone Planet 1',
	  img:'90 Alone Planet 1.jpg',
	  price:20,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'CYSL3HYV2CKQE'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Space Painting 3',
	  img:'91 Space Painting 3.jpg',
	  price:15,
	  sold:1,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Spiral Nebula',
	  img:'92 Spiral Nebula.jpg',
	  price:25,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'FND4EKCHW3S8U'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Alone Planet 2',
	  img:'93 Alone Planet 2.jpg',
	  price:20,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'BXN8HV7SFVYTL'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Pika Date',
	  img:'94 Pika Date.jpg',
	  price:20,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'Q59NSEQQRQSSY'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Redemption Road',
	  img:'95 Redemption Road.jpg',
	  price:15,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'42V9KGDJCB7Z8'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Halloween Fright',
	  img:'96 Halloween Fright.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'PC3BFFJCQ77UE'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Satellite View of Alien Planet',
	  img:'97 Satellite View of Alien Planet.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'7HMGLANQLMWJU'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Two Moons',
	  img:'98 Two Moons.jpg',
	  price:15,
	  sold:0,
	  material:'Spray Paint on Posterboard',
	  size:'20x18 in',
	  description: 'An Original Calamari',
	  buycode:'XG2WF5SQXFQDJ'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Pennywise',
	  img:'99 Pennywise.jpg',
	  price:250,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'16x20 in',
	  description: 'An Original Calamari',
	  buycode:'9ZGYQ9NLEBMXL'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	},
	{
	  name:'Beach',
	  img:'100 Beach.jpg',
	  price:30,
	  sold:0,
	  material:'Acrylic on Canvas',
	  size:'12x12 in',
	  description: 'An Original Calamari',
	  buycode:'7DSQSMPDBXPSY'  ,
	  type: "painting",
	  creator: "Robert Calamari"
	}
];